config/routes.rb
Projectlog::Application.routes.draw do
  root :to => 'dashboard#show'
    
  resources :transactions do
    collection do
      get 'reports/monthly', :action => 'monthly_report'
      get 'find_by_note'
    end
  end
  resources :subscriptions, :only => [:new, :create, :edit, :update] do
    collection do
      delete 'cancel'
      get 'current'
      get 'modify'
      put 'reactivate'
      get 'card_declined'
      get 'upgrade_required'
    end
    
    member do
      get 'success'
    end
  end
  get 'subscriptions/:slug/payments/:code', :controller => 'subscriptions', :action => 'receipt', :as => 'receipt_subscription_payment'
  
  resources :categories do
    member do
      get 'expenses'
    end
  end

  resource :dashboard do
    resources :activities, :controller => "dashboard/activities"
  end

  resources :project_statuses
  resources :profiles, :contacts
  
  resource :plan, :only => [:edit, :update]
  
  resources :customers do 
    resources :contacts
    resources :projects, :except => [:index]
    member do
      get 'projects', :to => "projects#by_customer"
    end
  end
  
  resources :invoices do
    member do
      get 'shared'
      get 'add_line_item'
      get 'prepare_email'
      post 'send_email'
      post 'sort'
    end
    collection do
      get 'overdue'
      post 'create_line_item'
      delete 'delete_line_item/:id', :action => 'delete_line_item'
    end
    resources :payments
  end
  
  resources :projects do
    collection do
      get 'closed'
      get 'quick'
    end
    
    resources :activities
    
    member do
      get 'expenses'
    end
  end
  
  resources :activities
  resources :transactions
  
  resources :reports do
    collection do
      get 'search'
    end
    member do
      get 'shared'
      post 'shared/approve', :action => 'approve'
    end
    resources :emails, :only => [ :new, :create ], :controller => 'reports/emails' do
      get 'contacts', :on => :collection
    end
  end
  
  resources :reports do
    member do
      post :timesheet
      put :approve
    end
  end
  
  resources :announcements, :only => [ :show ] do
    member { put :hide }
  end
  
  namespace :administr8te do
    resource :dashboard, :only => [ :show ], :controller => 'dashboard'
    resource :settings
    resources :clients, :only => [ :index ] do
      member do
        get 'summary'
        get 'profile'
        get 'transactions'
        get 'history'
      end
    end
    resources :plans
    resources :announcements
    resources :emailings
    resources :subscriptions, :only => [:index, :show]
    get '/audit', :controller => :audit_trails, :action => :index
    resource :logs, :only => [ :show ]
  end
  
  # allow "/users/login" and "/login"
  devise_for :user, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout" }, 
                    :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get '/register', :to => 'registrations#new'
    get '/login', :to => 'devise/sessions#new'
    get '/logout', :to => 'devise/sessions#destroy'
  end
  post '/paypal/ipn' => 'paypal#ipn'
  match '/settings' => 'profiles#edit', :as => 'settings'
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  include PaypalProRecurring::Subscribable
  include ActionView::Helpers::DateHelper
  
  belongs_to :plan
  belongs_to :user
  has_many :subscription_transactions
  
  attr_accessor :card_name, :card_number, :card_code, :card_expiration, :do_validate_card
  
  validates :plan_id, :card_name, :card_number, :card_code, :card_expiration, :presence => true, :if => Proc.new{|s| !s.do_validate_card.blank?}
  after_validation :generate_slug
  before_create :extract_card_type
  
  def to_param
    slug
  end
  
  def activate
    puts "activate"
    self.active = true
    self.save!
    user.current_subscription = self
    user.plan_id = self.plan_id
    user.save!
  end
  
  def deactivate
    puts "deactivate"
    # revert to free plan
    self.active = false
    self.save!
    
    user.current_subscription = nil
    user.plan_id = Plan.find_by_name("Free").id
    user.save!
  end
  
  def handle_gateway_response(subscription, request_type, response_type, response)
    puts "Request paypal #{request_type}"
    puts "Response #{response_type}"
  end
  
  def credit_card
    credit_card = ActiveMerchant::Billing::CreditCard.new(
      :first_name         => card_name.strip.split(/\s+/).first,
      :last_name          => card_name.strip.split(/\s+/).last,
      :number             => card_number,
      :month              => card_expiration['month'],
      :year               => card_expiration['year'],
      :verification_value => card_code)
  end
  
  def profile_options
    generate_slug
    opts = {
      :currency => "USD",
      :credit_card => credit_card,
      :amount => plan.price * 100, # amount in cents
      :start_date => start_date.nil? ? Time.now : start_date,
      :profile_reference => slug,
      :description => plan.description,
      :period => plan.frequency,
      :frequency => 1,
      :email => user.email,
      :max_failed_payments => Settings['max_failed_payments'],
      :auto_bill_outstanding => Settings['auto_bill_outstanding']
    }
  end

  def create_audit
    AuditTrail.create(:user_id => user_id, :action => 'subscribed', :message => "to the #{plan.name} plan (after #{distance_of_time_in_words(created_at-user.created_at)})")
  end
  
  def update_audit
    AuditTrail.create(:user_id => user_id, :action => 'updated', :message => "subscription")
  end
  
  def cancel_audit
    AuditTrail.create(:user_id => user_id, :action => 'canceled', :message => "subcscription from the #{plan.name} plan (#{distance_of_time_in_words_to_now(created_at)} old)")
  end
  
  def reactivate_audit
    AuditTrail.create(:user_id => user_id, :action => 'reactivated', :message => "subcscription to the #{plan.name} plan")
  end
  
  def card_type_name
    if card_type == 'master'
      'mastercard'
    else
      card_type
    end
  end
  
private
  
  def extract_card_type
    cc = credit_card
    cc.valid? # let active merchant determine credit card type for us
    self.card_type = cc.type
    self.currency = "USD"
  end
  
  def generate_slug
    self.slug = Devise.friendly_token.downcase if slug.nil?
  end
  
end

app/controllers/administr8te/subscriptions_controller.rb
class Administr8te::SubscriptionsController < Administr8te::BaseController
  set_tab :admin_subscriptions
  helper_method :sort_column, :sort_direction
  
  def index
    @subscriptions = SubscriptionTransaction.search(params[:search]).order(sort_column + " " + sort_direction).page(params[:page]).per(10) 
  end
  
private

  def sort_column
    SubscriptionTransaction.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_plans, :only => [:new, :create]
  
  def new
    @subscription = current_user.subscriptions.build
  end
  
  def create
    @subscription = current_user.subscriptions.build(params[:subscription])
    @subscription.plan = Plan.find_by_name(Settings['subscriptions.default_costing_plan'])
    @subscription.start_date = Time.now
    @subscription.do_validate_card = true
    if @subscription.save
      SubscriptionsMailer.new_subscription_email(@subscription).deliver
      AdminMailer.new_subscription_email(@subscription).deliver
      @subscription.create_audit
      redirect_to success_subscription_url(@subscription), :notice => "Your subscription has been successfully updated."
    else
      render :action => :new
    end
  end
  
  def edit
    @subscription = current_user.current_subscription
  end
  
  def update
    @subscription = current_user.current_subscription
    @subscription.assign_attributes(params[:subscription])
    @subscription.do_validate_card = true
    if @subscription.valid?
      new_profile_options = @subscription.profile_options.merge(profile_id: @subscription.paypal_profile_id)
      if @subscription.update_profile(new_profile_options)
        SubscriptionsMailer.update_subscription_email(@subscription).deliver
        @subscription.update_audit
        redirect_to success_subscription_url(@subscription), notice: "Your subscription has been successfully updated."
      else
        render action: :edit
      end
    else
      render action: :edit
    end
  end
  
  def cancel
    # cancel on due date
    @subscription = current_user.current_subscription
    if @subscription.cancel(:timeframe => :renewal)
      SubscriptionTransactionsMailer.subscription_cancelled_email(@subscription).deliver
      AdminMailer.cancel_subscription_email(@subscription).deliver
      @subscription.cancel_audit
      redirect_to current_subscriptions_url, :notice => "Your subscription has been cancelled successfully."
    else
      redirect_to edit_subscription_url(@subscription), :alert => "Failed to cancel your subscription, please contact system administrator."
    end
  end
  
  def current
    @subscription = current_user.current_subscription
  end
  
  def modify
    @subscription = current_user.subscriptions.build(card_name: 'John Doe', card_number: '5468402944292202')
  end
  
  def reactivate
    @subscription = current_user.current_subscription
    @subscription.assign_attributes(params[:subscription])
    @subscription.do_validate_card = true
    if @subscription.valid?
      if @subscription.modify(params[:subscription].merge(:plan => @subscription.plan, :timeframe => current_user.plan.costing? ? :renewal : :now))
        @subscription.card_declined = false
        @subscription.save
        @subscription.reactivate_audit
        redirect_to current_subscriptions_url, :notice => "Your subscription has been reactivated successfully."
      else
        redirect_to current_subscriptions_url, alert: "Failed to reactivate your subscription, please contact system administrator."
      end
    else
      render :action => :modify
    end
  end
  
  def success
    @transaction = current_user.subscriptions.find_by_slug(params[:id])
  end
  
  def receipt
    @subscription = current_user.current_subscription
    @transaction = @subscription.subscription_transactions.find_by_code(params[:code])
    
    respond_to do |format|
      format.pdf { render :text => PDFKit.new(render_to_string(:action => 'receipt.html', :layout => 'pdfattach')).to_pdf }
      format.html
    end
  end
  
  def upgrade_required
    render :layout => 'login'
  end
  
private
  
  def load_plans
    @plans = Plan.active.displayable.where("price > 0").order('price ASC') 
  end
end

app/views/subscriptions/card_declined.html.erb
your card has been declined, please <%= link_to 'update card', modify_subscriptions_path %>

app/views/subscriptions/current.html.erb
<h1>Payment History</h1>
<% if current_user.current_subscription %>
  <% if current_user.subscription_transactions.blank? and !current_user.current_subscription.cancelled? %>
    <p>You will find your billing history here as soon as we hear back from our payment gateway. It may take a few hours but this is normal.</p>
  <% else %>
    <table>
    <% current_user.subscription_transactions.order('created_at DESC').each do |transaction| %>
      <tr>
        <td><%= transaction.created_at.strftime("%B %d, %Y") %></td>
        <td>Transaction #<%= transaction.code %></td>
        <td><%= number_to_currency(transaction.amount) %></td>
        <td><%= link_to "Printable Receipt (PDF)", receipt_subscription_payment_path(current_user.current_subscription, transaction.code, format: 'pdf') %></td>
      </tr>
    <% end %>
    </table>
  <% end %>
<% end %>

<h2>Your current plan: <%= current_user.plan.name %></h2>
<% if current_user.current_subscription %>
  <% if current_user.current_subscription.cancelled? %>
    <h2>You've cancelled your subscription. You can continue to use the <%= current_user.current_subscription.plan.name %> plan until it expires on <%= current_user.current_subscription.modify_on.strftime("%B %d, %Y") %>.</h2>
    <p><%= link_to 'Reactivate', modify_subscriptions_path, :class => 'buttonorange' %></p>
  <% else %>
    <h2>Next payment will be processed on <%= current_user.current_subscription.next_payment_due.strftime("%B %d, %Y") %>.</h2>
    <p><%= link_to 'Edit Subscription & Payment Method', edit_subscription_path(current_user.current_subscription), :class => 'buttonorange' %></p>
  <% end %>
<% else %>
  <p><%= link_to 'Upgrade', new_subscription_path, :class => 'buttonorange' %></p>
<% end %>

app/views/subscriptions/edit.html.erb
<p class="info" style="font-size:13px">Change your subscription information or cancel your subscription. You can also return to <%= link_to 'Current Subscription', current_subscriptions_path %></p>

<h1>Change Payment Method</h1>
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation" class="alert">
      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="billing_fields" class="inline-form">
    <div class="field">
      <%= f.label :card_name, "Name on Card", :class => 'mandatory' %>
      <%= f.text_field :card_name  %>
    </div>
    <div class="field">
      <%= f.label :card_number, "Card Number", :class => 'mandatory' %>
      <%= f.text_field :card_number %>
    </div>
    <div class="field">
      <%= f.label :card_code, "Security Code (CVV)", :class => 'mandatory' %>
      <%= f.text_field :card_code, :value => "" %> <%= image_tag('cvv.png', :alt => 'CVV', :id => 'cvv') %>
    </div>
    <div class="field" style='clear:both;'>
      <%= label_tag :card_month, "Expires on", :class => 'mandatory' %>
      <%= select_date @subscription.card_expiration ? Date.new(@subscription.card_expiration["year"].to_i, @subscription.card_expiration["month"].to_i, 1) : nil, :prefix => "subscription[card_expiration]", :add_month_numbers => true, :discard_day => true, :order => [:month, :year], :start_year => Time.now.year, :end_year => Time.now.year + 15 %>
    </div>
    <div id="stripe_error">
      <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
    </div>
    <div class="actions">
      <p class="submit"><%= submit_tag "Update Payment", 'data-disable-with' => "Processing..." %></p>
    </div>
  </div>
<% end %>

<h1>Or cancel your subscription</h1>
<%= link_to 'Cancel Subscription', cancel_subscriptions_path, :data => {:confirm => "Are you sure you want to cancel your subscription?"}, :method => :delete, :class => 'buttonorange' %>

app/views/subscriptions/modify.html.erb
<h1>Reactivate subscription</h1>

<p class="info" style="font-size:13px">Your subscription will become effective on <%= current_user.current_subscription.next_payment_due.strftime("%B %d, %Y") %>.</p>

<%= form_for(@subscription, :url => reactivate_subscriptions_path, :method => :put) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation" class="alert">
      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="billing_fields" class="inline-form">
    <div class="field">
      <%= f.label :card_name, "Name on Card", :class => 'mandatory' %>
      <%= f.text_field :card_name  %>
    </div>
    <div class="field">
      <%= f.label :card_number, "Card Number", :class => 'mandatory' %>
      <%= f.text_field :card_number %>
    </div>
    <div class="field">
      <%= f.label :card_code, "Security Code (CVV)", :class => 'mandatory' %>
      <%= f.text_field :card_code, :value => "" %> <%= image_tag('cvv.png', :alt => 'CVV', :id => 'cvv') %>
    </div>
    <div class="field">
      <%= label_tag :card_month, "Expires on", :class => 'mandatory' %>
      <%= select_date @subscription.card_expiration ? Date.new(@subscription.card_expiration["year"].to_i, @subscription.card_expiration["month"].to_i, 1) : nil, :prefix => "subscription[card_expiration]", :add_month_numbers => true, :discard_day => true, :order => [:month, :year], :start_year => Time.now.year, :end_year => Time.now.year + 15 %>
    </div>
    <div id="stripe_error">
      <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
    </div>
    <div class="actions">
      <p class="submit"><%= submit_tag "Reactivate", 'data-disable-with' => "Processing..." %></p>
    </div>
  </div>
<% end %>

app/views/subscriptions/new.html.erb
<h1>New Subscription
  <span class='floatr'><%= image_tag('lock_active.png', :alt => 'secure page', :style => 'margin-top:5px;') %></span>
</h1>

<p id='trial_status'>You have <%= content_tag(:span, "#{pluralize(current_user.trial_days_left, 'day')} left", :id => 'days_left') %> on your Unlimited Free Trial</p>

<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation" class="alert">
      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="select-plan">
    <ul class="card-entries">
      <% @plans.each do |plan| %>
        <li class="card no-link <%= cycle('odd', 'even') %>">
          <div class="card-inner">
            <h1><%= plan.name %>
        	  <span class='floatr'>$<%= plan.price.round(0) %> / <%= plan.frequency %></span>
        	</h1>
        	<p class="tagline"><%= simple_format(plan.description) %></p>
          </div>
        </li>
      <% end %>
      <li class="card no-link even">
        <div class="card-inner mktg">
          <h1>You're in good hands</h1>
      	  <ul class="tagline">
      	    <li>Upgrade / Downgrade anytime</li>
      	    <li>Secure Payment</li>
      	    <li>Friendly customer support</li>
      	  </ul>
        </div>
      </li>
    </ul>
  </div>
  
  <div id="billing_fields" class="inline-form">
    <div class="field">
      <%= f.label :card_name, "Name on Card", :class => 'mandatory' %>
      <%= f.text_field :card_name  %>
    </div>
    <div class="field">
      <%= f.label :card_number, "Card Number", :class => 'mandatory' %>
      <%= f.text_field :card_number %>
    </div>
    <div class="field">
      <%= f.label :card_code, "Security Code (CVV)", :class => 'mandatory' %>
      <%= f.text_field :card_code, :value => "" %> <%= image_tag('cvv.png', :alt => 'CVV', :id => 'cvv') %>
    </div>
    <div class="field">
      <%= label_tag :card_month, "Expires on", :class => 'mandatory' %>
      <%= select_date @subscription.card_expiration ? Date.new(@subscription.card_expiration["year"].to_i, @subscription.card_expiration["month"].to_i, 1) : nil, :prefix => "subscription[card_expiration]", :add_month_numbers => true, :discard_day => true, :order => [:month, :year], :start_year => Time.now.year, :end_year => Time.now.year + 15 %>
    </div>
    <div id="stripe_error">
      <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
    </div>
    <div class="actions">
      <p class="submit"><%= submit_tag "Confirm Subscription", 'data-disable-with' => "Processing..." %></p>
    </div>
  </div>
<% end %>

app/views/subscriptions/receipt.erb
<div style="line-height:50px;">
  <h2>Projectlog Subscription Receipt
    <span style="float:right;"><img src='<%= Rails.root.join("app", "assets", "images", "logo.png") %>' width='150px'></span>
  </h2>
</div>

<p>Here is the invoice for your Projectlog subscription. Paid in full up to date. No payment is due.</p><br />

<p><b>Date:</b> <%= @transaction.created_at.strftime("%d-%m-%Y %H:%M") %></p>
<p><b>Transaction Number:</b> <%= @transaction.code %></p>
<p><b>Plan:</b> <%= @transaction.subscription.plan.name %></p>
<p><b>Amount charged:</b> $<%= @transaction.amount %> (USD)</p>
<p><b>Company:</b> <%= @transaction.user.profile.company %></p>
<p><b>Name:</b> <%= @transaction.user.full_name %></p>
<p><b>Card Type:</b> <%= @transaction.subscription.card_type_name %></p>

<br />
<%= simple_format(Settings.defaults['subscription_receipt_signature']) %>

app/views/subscriptions/receipt.html.erb
<h1>Projectlog Subscription Receipt</h1>

<p>Here is the invoice for your Projectlog subscription. Paid in full up to date. No payment is due.</p><br />

<p><b>Date:</b> <%= @transaction.created_at.strftime("%d-%m-%Y %H:%M") %></p>
<p><b>Transaction Number:</b> <%= @transaction.code %></p>
<p><b>Plan:</b> <%= @transaction.subscription.plan.name %></p>
<p><b>Amount charged:</b> $<%= @transaction.amount %> (USD)</p>
<p><b>Company:</b> <%= @transaction.user.profile.company %></p>
<p><b>Name:</b> <%= @transaction.user.full_name %></p>
<p><b>Card Type:</b> <!%= @transaction.card_type %></p>

<br />
Projectlog<br />
65 Blvd Fournier<br />
Gatineau, QC, J8X3P6<br />
Canada<br /><br />

contact@getprojectlog.com<br />
http://getprojectlog.com<br /><br />

Thank you for subscribing!

app/views/subscriptions/success.html.erb
<div id="image">
  <%= image_tag('check.png') %><br />
  <p><%= @transaction.user.full_name %>, thank you for choosing the <%= @transaction.plan.name %> plan.</p>
  <p>We sent you an email to confirm this change as well.</p>
  <p><%= link_to 'Manage Subscription', current_subscriptions_path, :class => 'buttonorange' %></p>
</div>

app/views/subscriptions/upgrade_required.html.erb
<div class="focus">
  <h2>You've reached the limit of your current plan.</h2>
  <p class='tagline'>If you wish to continue please upgrade.<br />
     It's <b>quick & secure</b> and gives you <b>full access</b>.
  </p>
  <p style='text-align:center;'><%= link_to 'Upgrade Plan', new_subscription_path, :class => 'buttonorange' %> or 
  <%= link_to 'Return', root_path, :class => 'cancel' %></p>
</div>