config/routes.rb
Projectlog::Application.routes.draw do
  root :to => 'dashboard#show'
    
  resources :transactions do
    collection do
      get 'reports/monthly', :action => 'monthly_report'
      get 'find_by_note'
    end
  end
  resources :subscriptions, :only => [:new, :create, :edit, :update] do
    collection do
      delete 'cancel'
      get 'current'
      get 'modify'
      put 'reactivate'
      get 'card_declined'
      get 'upgrade_required'
    end
    
    member do
      get 'success'
    end
  end
  get 'subscriptions/:slug/payments/:code', :controller => 'subscriptions', :action => 'receipt', :as => 'receipt_subscription_payment'
  
  resources :categories do
    member do
      get 'expenses'
    end
  end

  resource :dashboard do
    resources :activities, :controller => "dashboard/activities"
  end

  resources :project_statuses
  resources :profiles, :contacts
  
  resource :plan, :only => [:edit, :update]
  
  resources :customers do 
    resources :contacts
    resources :projects, :except => [:index]
    member do
      get 'projects', :to => "projects#by_customer"
    end
  end
  
  resources :invoices do
    member do
      get 'shared'
      get 'add_line_item'
      get 'prepare_email'
      post 'send_email'
      post 'sort'
    end
    collection do
      get 'overdue'
      post 'create_line_item'
      delete 'delete_line_item/:id', :action => 'delete_line_item'
    end
    resources :payments
  end
  
  resources :projects do
    collection do
      get 'closed'
      get 'quick'
    end
    
    resources :activities
    
    member do
      get 'expenses'
    end
  end
  
  resources :activities
  resources :transactions
  
  resources :reports do
    collection do
      get 'search'
    end
    member do
      get 'shared'
      post 'shared/approve', :action => 'approve'
    end
    resources :emails, :only => [ :new, :create ], :controller => 'reports/emails' do
      get 'contacts', :on => :collection
    end
  end
  
  resources :reports do
    member do
      post :timesheet
      put :approve
    end
  end
  
  resources :announcements, :only => [ :show ] do
    member { put :hide }
  end
  
  namespace :administr8te do
    resource :dashboard, :only => [ :show ], :controller => 'dashboard'
    resource :settings
    resources :clients, :only => [ :index ] do
      member do
        get 'summary'
        get 'profile'
        get 'transactions'
        get 'history'
      end
    end
    resources :plans
    resources :announcements
    resources :emailings
    resources :subscriptions, :only => [:index, :show]
    get '/audit', :controller => :audit_trails, :action => :index
    resource :logs, :only => [ :show ]
  end
  
  # allow "/users/login" and "/login"
  devise_for :user, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout" }, 
                    :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get '/register', :to => 'registrations#new'
    get '/login', :to => 'devise/sessions#new'
    get '/logout', :to => 'devise/sessions#destroy'
  end
  post '/paypal/ipn' => 'paypal#ipn'
  match '/settings' => 'profiles#edit', :as => 'settings'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :transactions
  attr_accessible :name, :user_id
  validates_presence_of :name
  validates_uniqueness_of :name, :scope => :user_id
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @categories = current_user.categories.order(:name).where("lower(name) like ?", "%#{params[:term].downcase}%")
    
    render json: @categories.map(&:name)
  end

  def show
    @category = current_user.categories.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @category = current_user.categories.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  def edit
    @category = current_user.categories.find(params[:id])
  end

  def create
    @category = current_user.categories.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.js
      else
        format.html { render :action => "new" }
        format.js
      end
    end
  end

  def update
    @category = current_user.categories.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy
    
    respond_to do |format|
      format.html { redirect_to categories_url }
    end
  end
  
  def expenses
    @category = current_user.categories.find(params[:id])
    current_period = current_user.profile.fiscal_period
    unless params[:fiscal_year].blank?
      period = Profile.to_period(params[:fiscal_year])
      current_period = period unless period.nil?
    end
    @transactions = @category.transactions.by_period(current_period).order('date DESC')
    @periods = current_user.profile.fiscal_range
    @fiscal_year = Profile.period_to_s(current_period.first, current_period.last)
  end
end

app/views/categories/expenses.html.erb
<ul id="sub-menu">
  <%= link_to '← All Transactions', transactions_path %>
</ul>

<h1>All Transactions in <%= @category.name %>
  <% if @periods.size > 1 %>
  <div class='floatr'>
    <%= select_tag 'fiscal_year', options_for_select(@periods, @fiscal_year), "data-url" => expenses_category_url(@category) %>
  </div>
  <% end %>
</h1>

<% if @transactions.any? %>  
  <div id="pl_summary">
    <div class='card-inner'>
	  <span id="total_income">Total Incomes: <span id="curr_income"><%= number_to_currency(Transaction.total_incomes(@transactions)) %></span></span>
	  <span id="total_expense">Total Expenses: <span id="curr_expense"><%= number_to_currency(Transaction.total_expenses(@transactions)) %></span></span>
    </div>
  </div>	 
  
  <% @transactions.group_by{|t| t.date.strftime "%Y %b" }.each do |date_str,transactions| %>
    <h2 class="date_period">
      <%= date_str %>
      <span class="total_right">
  	  Inc.: <span class="monthly_incomes"><%= number_to_currency(Transaction.total_incomes(transactions)) %></span> | 
  	  Exp.: <span class="monthly_expenses"><%= number_to_currency(Transaction.total_expenses(transactions)) %></span>
  	</span>
    </h2>
    <ul>
    <% transactions.each do |transaction| %>
      <li class="transactions_list">
        <span id="t_date"><%= l transaction.date, :format => :short %></span>
  	    <span id="t_type"><% if transaction.expense? %><span class="t_expense">Exp.</span><% else %><span class="t_income">Inc.</span> <% end %></span>
        <span id="t_amount"><%= link_to number_to_currency(transaction.total), edit_transaction_path(transaction), remote: true %></span>
        <span id="t_note_long"><%= truncate(transaction.note, :length => 70) %></span>
  	    <span id="t_project"><%= link_to transaction.project.title, expenses_project_path(transaction.project) unless transaction.project.nil? %></span>
  	  </li>
    <% end %>
    </ul>
  <% end %>
  
<% else %>
  <p class="no-occurence">No transactions found for this period (<%= @fiscal_year %>)</p>
<% end %>
<script type="text/javascript" charset="utf-8">
  $(function() {
    Transactions.MonthlyReport.init();
  });
</script>