config/routes.rb
Projectlog::Application.routes.draw do
  root :to => 'dashboard#show'
    
  resources :transactions do
    collection do
      get 'reports/monthly', :action => 'monthly_report'
      get 'find_by_note'
    end
  end
  resources :subscriptions, :only => [:new, :create, :edit, :update] do
    collection do
      delete 'cancel'
      get 'current'
      get 'modify'
      put 'reactivate'
      get 'card_declined'
      get 'upgrade_required'
    end
    
    member do
      get 'success'
    end
  end
  get 'subscriptions/:slug/payments/:code', :controller => 'subscriptions', :action => 'receipt', :as => 'receipt_subscription_payment'
  
  resources :categories do
    member do
      get 'expenses'
    end
  end

  resource :dashboard do
    resources :activities, :controller => "dashboard/activities"
  end

  resources :project_statuses
  resources :profiles, :contacts
  
  resource :plan, :only => [:edit, :update]
  
  resources :customers do 
    resources :contacts
    resources :projects, :except => [:index]
    member do
      get 'projects', :to => "projects#by_customer"
    end
  end
  
  resources :invoices do
    member do
      get 'shared'
      get 'add_line_item'
      get 'prepare_email'
      post 'send_email'
      post 'sort'
    end
    collection do
      get 'overdue'
      post 'create_line_item'
      delete 'delete_line_item/:id', :action => 'delete_line_item'
    end
    resources :payments
  end
  
  resources :projects do
    collection do
      get 'closed'
      get 'quick'
    end
    
    resources :activities
    
    member do
      get 'expenses'
    end
  end
  
  resources :activities
  resources :transactions
  
  resources :reports do
    collection do
      get 'search'
    end
    member do
      get 'shared'
      post 'shared/approve', :action => 'approve'
    end
    resources :emails, :only => [ :new, :create ], :controller => 'reports/emails' do
      get 'contacts', :on => :collection
    end
  end
  
  resources :reports do
    member do
      post :timesheet
      put :approve
    end
  end
  
  resources :announcements, :only => [ :show ] do
    member { put :hide }
  end
  
  namespace :administr8te do
    resource :dashboard, :only => [ :show ], :controller => 'dashboard'
    resource :settings
    resources :clients, :only => [ :index ] do
      member do
        get 'summary'
        get 'profile'
        get 'transactions'
        get 'history'
      end
    end
    resources :plans
    resources :announcements
    resources :emailings
    resources :subscriptions, :only => [:index, :show]
    get '/audit', :controller => :audit_trails, :action => :index
    resource :logs, :only => [ :show ]
  end
  
  # allow "/users/login" and "/login"
  devise_for :user, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout" }, 
                    :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get '/register', :to => 'registrations#new'
    get '/login', :to => 'devise/sessions#new'
    get '/logout', :to => 'devise/sessions#destroy'
  end
  post '/paypal/ipn' => 'paypal#ipn'
  match '/settings' => 'profiles#edit', :as => 'settings'
end

app/controllers/transactions_controller.rb
# encoding: UTF-8

class TransactionsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction
  set_tab :accounting

  before_filter :check_accessible, :only => [:index, :new]
  before_filter :check_limit, :only => [:new]

  def index
    @transactions = current_user.transactions.includes(:project, :category).order(sort_column + " " + sort_direction).page(params[:page]).per(20)
    @transactions = @transactions.by_keyword(params[:search]) unless params[:search].blank?
    @transactions = @transactions.by_category(params[:category_id]) unless params[:category_id].blank?
    if !params[:start_date].blank? and !params[:end_date].blank?
      @transactions = @transactions.by_period((params[:start_date]..params[:end_date]))
    elsif !params[:start_date].blank?
      @transactions = @transactions.from_date(params[:start_date])
    elsif !params[:end_date].blank?
      @transactions = @transactions.to_date(params[:end_date])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
      format.js
      format.csv {
        content = Transaction.to_csv(current_user.transactions.includes(:project, :category))
        content = content.encode("UTF-8")
        send_data content,
          filename:    "transactions.csv",
          type:        "text/csv; charset=utf-8; header=present",
          disposition: "attachment"
      }
    end
  end

  def show
    @transaction = current_user.transactions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  def new
    @transaction = current_user.transactions.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
      format.js
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
      format.js
    end
  end

  def create
    @transaction = current_user.transactions.build
    @transaction.assign_attributes(params[:transaction])
    @is_quick = params[:quick].present?
    respond_to do |format|
      if @transaction.save
        @transactions = current_user.transactions.order("created_at DESC").page(1).per(20)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    @transaction = current_user.transactions.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :ok }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @transaction = current_user.transactions.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :ok }
    end
  end

  def monthly_report
    current_period = current_user.profile.fiscal_period
    unless params[:fiscal_year].blank?
      period = Profile.to_period(params[:fiscal_year])
      current_period = period unless period.nil?
    end
    @transactions = current_user.transactions.by_period(current_period).includes(:category, :project).order("date DESC")
    @periods = current_user.profile.fiscal_range
    @fiscal_year = Profile.period_to_s(current_period.first, current_period.last)
  end

  def find_by_note
    @transactions = current_user.transactions.order(:note).where("lower(note) like ?", "%#{params[:term].downcase}%")

    render json: @transactions.map(&:note).uniq
  end

private

  def sort_column
    Transaction.column_names.include?(params[:sort]) ? params[:sort] : "date"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

  def check_accessible
    unless current_user.admin?
      unless current_permissions[:transaction][:accessible]
        return redirect_to upgrade_required_subscriptions_url, alert: "You cannot access this page. Please upgrade plan."
      end
    end
  end

  def check_limit
    unless current_user.admin?
      if current_permissions[:transaction][:limit] > 0 && current_user.transactions.count >= current_permissions[:transaction][:limit]
        return redirect_to upgrade_required_subscriptions_url, alert: "You have reached max #{current_permissions[:transaction][:limit]} transactions for this plan. Please upgrade plan."
      end
    end
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def searching?(params)
    params[:search].present? || params[:category_id].present? || params[:start_date].present? || params[:end_date].present?
  end
  
  def humanize_search_params(params)
    str = []
    str << "matching '#{params[:search]}'" if params[:search].present?
    str << ("in " + (params[:category_id].empty? ? 'All categories' : Category.find(params[:category_id]).name)) if params[:category_id].present?
    str << "from '#{params[:start_date]}'" if params[:start_date].present?
    str << "to '#{params[:end_date]}'" if params[:end_date].present?
    str.join(" ")
  end
end

app/views/transactions/_fields.js.erb
<%= form_for(@transaction, :remote => true) do |f| %>

  <%= hidden_field_tag :tax1, current_user.profile.try(:tax1) || 0,  :id => "tax1_rate" %>
  <%= hidden_field_tag :tax2, current_user.profile.try(:tax2) || 0, :id => "tax2_rate" %>
  <%= hidden_field_tag :compound, current_user.profile.try(:compound) || false, :id => "compound" %>
  <div class="inline-form">
    <div class="field">
      <%= f.label :date, :class => "mandatory" %>
      <%= f.text_field :date, :class => 'date', :autofocus => true %>
    </div>
    <div class="field">
      <%= f.label :expense, "Type", :class => "mandatory" %>
      <%= f.radio_button :expense, true %> Expense <%= f.radio_button :expense, false %> <span>Income</span> <%= clear %>
    </div>
    <div class="field">
      <%= f.label :note, "Description", :class => "mandatory" %>
      <%= f.text_field :note, data: {autocomplete_source: find_by_note_transactions_path}, style: "max-width:286px;" %>
    </div>
    <div class="field">
      <%= f.label :total, :class => "mandatory" %>
      <%= f.text_field :total, :size => 8, :id => "total" %>
    </div>
    <div class="field">
	  <%= f.label :tax2, current_user.profile.tax1_label.present? ? current_user.profile.tax1_label : 'Tax 1' %>
      <%= f.text_field :tax1, :size => 8, :id => "tax1" %>
    </div>
    <div class="field">
	  <%= f.label :tax2, current_user.profile.tax2_label.present? ? current_user.profile.tax2_label : 'Tax 2' %>
      <%= f.text_field :tax2, :size => 8, :id => "tax2" %>
    </div>
    <div class="field">
      <%= f.label :category_name, 'Category' %>
	  <%= f.text_field :category_name, data: {autocomplete_source: categories_path} %>
    </div>
    <div class="field">
      <%= f.label :project_id %>
      <%= f.collection_select(:project_id, current_user.projects.order('title ASC'), :id, :title_and_client, :include_blank => 'Please Select') %>
    </div>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $("#transaction_date").focus();
    Transactions.Form.init(".edit_transaction");
  });
</script>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag :tax1, current_user.profile.try(:tax1) || 0,  :id => "tax1_rate" %>
  <%= hidden_field_tag :tax2, current_user.profile.try(:tax2) || 0, :id => "tax2_rate" %>
  <%= hidden_field_tag :compound, current_user.profile.try(:compound) || false, :id => "compound" %>
<div class="inline-form">
  <div class="field">
    <%= f.label :date, :class => "mandatory" %>
    <%= f.text_field :date, :class => 'date', :autofocus => true %>
  </div>
  <div class="field">
    <%= f.label :expense, "Type", :class => "mandatory" %>
    <%= f.radio_button :expense, true %> Expense <%= f.radio_button :expense, false %> <span>Income</span> <%= clear %>
  </div>
  <div class="field">
    <%= f.label :note, "Description", :class => "mandatory" %>
    <%= f.text_field :note, data: {autocomplete_source: find_by_note_transactions_path} %>
  </div>
  <div class="field">
    <%= f.label :total, :class => "mandatory" %>
    <%= f.text_field :total, :size => 8, :id => "total" %>
  </div>
  <div class="field">
	<%= f.label :tax2, current_user.profile.tax1_label.present? ? current_user.profile.tax1_label : 'Tax 1' %>
    <%= f.text_field :tax1, :size => 8, :id => "tax1" %>
  </div>
  <div class="field">
	<%= f.label :tax2, current_user.profile.tax2_label.present? ? current_user.profile.tax2_label : 'Tax 2' %>
    <%= f.text_field :tax2, :size => 8, :id => "tax2" %>
  </div>
  <div class="field">
    <%= f.label :category_name, 'Category' %>
	<%= f.text_field :category_name, data: {autocomplete_source: categories_path} %>
  </div>
  <div class="field">
    <%= f.label :project_id %>
    <%= f.collection_select(:project_id, current_user.projects.order('title ASC'), :id, :title_and_client, :include_blank => 'Please Select') %>
  </div>
  <div class="actions">
    <p class="submit"><%= submit_or_cancel(f) %></p>
  </div>
</div>
<% end %>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $("#transaction_date").focus();
    Transactions.Form.init(".new_transaction");
  });
</script>

app/views/transactions/_quick.html.erb
<% transaction = current_user.transactions.new %>
<%= form_for(transaction, :method => :post, :remote => true) do |f| %>
  <%= hidden_field_tag :tax1, current_user.profile.try(:tax1) || 0,  :id => "tax1_rate" %>
  <%= hidden_field_tag :tax2, current_user.profile.try(:tax2) || 0, :id => "tax2_rate" %>
  <%= hidden_field_tag :compound, current_user.profile.try(:compound) || false, :id => "compound" %>

  <table class='borders'>
    <tr>
      <th id="t.date" style="">Date</th>
      <th id="t.amount" style="width: 100px;">Total</th>
      <th id="t.note">Description</th>
      <th></th>
    </tr>
    <tr class="transaction-fields row-one">
      <td><%= f.text_field :date, :class => "date", :tabindex => 1 %></td>
      <td><%= f.number_field :total, :class => "numbers", :id => "total", :tabindex => 2, :step => :any %></td>
      <td><%= f.text_field :note, data: {autocomplete_source: find_by_note_transactions_path}, :tabindex => 3 %></td>
      <td><span class="small submit"><%= f.submit 'Create', :name => @transactions.empty? ? "quick" : nil, "data-disable-with" => 'Create' %></span></td>
    </tr>
    <tr class="transaction-fields">
      <td style="vertical-align:top;"><%= f.radio_button(:expense, true) %> Expense<br> <%= f.radio_button(:expense, false) %> Income</td>
      <% if current_user.profile.any_taxes? %>
        <td style="vertical-align:top; word-wrap: break-word; width: 100px;">
          <% unless current_user.profile.tax1.blank? %>
            <%= current_user.profile.tax1_name(false) %><br><%= f.text_field :tax1, :class => "numbers", :id => "tax1", :step => :any %><br>
          <% end %>
          <% unless current_user.profile.tax2.blank? %>
            <%= current_user.profile.tax2_name(false) %><br><%= f.text_field :tax2, :class => "numbers", :id => "tax2", :step => :any %>
          <% end %>
        </td>
      <% end %>
      <td style="vertical-align:top;" colspan="<%= current_user.profile.any_taxes? ? '1' : '2' %>">
        Category
        <br>
        <%= f.text_field :category_name, data: {autocomplete_source: categories_path}, :tabindex => 4 %>
        <br>
        Project
        <br>
        <%= f.collection_select(:project_id, current_user.projects.order('title ASC'), :id, :title_and_client, {:prompt => true, :class => 'transaction_project'}, :tabindex => 5) %>
      </td>
      <td></td>
    </tr>
  </table>
<% end %>

app/views/transactions/_submenu.html.erb
<ul id="sub-menu">
  <%= link_to '← All Transactions', transactions_path %> |
  <%= link_to 'Edit', edit_transaction_path %> |
  <%= link_to 'Destroy', @transaction, :data => {:confirm => 'Are you sure?'}, :method => :delete %>
  <li class="buttonorange"><%= link_to '+ New Transaction', new_transaction_path %></li>
</ul>

app/views/transactions/_table_header.html.erb
<div id="transaction_toggle_search_form" class="floatl">
  <%= link_to "Show/Hide Advanced Search", "#", :id => "toggle_search_form" %>
</div>
<div id="transactions-search" class="floatr">	
  <span id="export" class="right">
    <%= form_tag transactions_path, :method => 'get', :id => "transactions_search" do %>
  	  <%= hidden_field_tag :direction, params[:direction] %>
  	  <%= hidden_field_tag :sort, params[:sort] %>
  	  <%= text_field_tag :search, params[:search] %>
	  <span class="small submit"><%= submit_tag "Search", :name => nil %></span>
	<% end %>
 </span>
</div>
<%= clear %>
<div id="transactions-advanced-search" style="display: none;" class="info">
  <h2>Advanced Search</h2>
  <%= form_tag "", :method => :get do %>
    <%= hidden_field_tag :form, "advanced" %>
    <p>Show transactions for <%= select_tag :category_id, options_for_select([["All Categories", ""]] + current_user.categories.map {|c| [c.name, c.id]}, params[:category_id]), :id => "quick_search_category_id" %>
    from <%= text_field_tag :start_date, params[:start_date], :size => 12, :class => "date" %>
    to <%= text_field_tag :end_date, params[:end_date], :size => 12, :class => "date" %>  
    <span class="submit"><%= submit_tag "Search", "data-disable-with" => 'Searching...', :name => nil %></span>
    <%= image_tag("indicator.gif", :class => "loading", :style => "display: none") %>  
  <% end %>
</div>

app/views/transactions/_transactions.html.erb
<% if @transactions.empty? %>
  <% if searching?(params) %>
    <%= render "table_header" %>
    <div class="no-occurence">
      <p>No transactions <%= humanize_search_params(params) %><br />
         <%= link_to 'Show all', transactions_path %>
      </p>
    </div>
  <% end %>
<% else %>
  <h1><%= searching?(params) ? "Listing transactions #{humanize_search_params(params)}" : "Transactions" %></h1>
  <%= render "table_header" %>
  <table id ="transactions" class="activities">
	<tr>
	  <th style='width:35px;'><%= sortable "expense", { :remote => true } %></th>
	  <th style='width:66px;'><%= sortable "date", { :remote => true } %></th>
	  <th style='width:84px;'><%= sortable "total", { :remote => true } %></th>
	  <th><%= sortable "note", {:remote => true } %></th>
	  <th><%= sortable "project_id", {:remote => true } %></th>
	  <th><%= sortable "category_id", {:remote => true } %></th>
	  <th style='width:55px;'></th>
	</tr>

	<% @transactions.each do |transaction| %>
	<tr id="row_for_transaction_<%= transaction.id %>">
	  <td><%= transaction.expense? ? content_tag(:span, 'Exp.', :class => 'expense') : content_tag(:span, 'Inc.', :class => 'income') %></td>
	  <td><%= l transaction.date, :format => :short %></td>
	  <td><%= number_to_currency(transaction.total) %></td>
	  <td><%= truncate(transaction.note, :length => 34) %></td>
	  <td><%= link_to transaction.project.title, expenses_project_path(transaction.project) unless transaction.project.nil? %></td>
	  <td><%= link_to transaction.category.name, expenses_category_path(transaction.category) unless transaction.category.nil? %></td>
	  <td><%= link_to 'Edit', edit_transaction_path(transaction), remote: true %>
		  <%= link_to image_tag("bin.png"), transaction, :data => { :confirm => 'Are you sure?' }, :method => :delete %>
	  </td>
	</tr>
	<% end %>
  </table>

  <div class="right">
    <%= paginate @transactions, :remote => true, :params => { controller: "transactions", action: "index", transaction_id: @transaction_id } %>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
  Transactions.Index.init();
</script>

app/views/transactions/create.js.erb
<% unless @transaction.errors.any? %>
  <% if @is_quick %>
    window.location = "<%= transactions_url %>";
  <% else %>
    $('#new-transaction-form').html('<%= escape_javascript(render 'quick') %>');
    $("#transactions").html("<%= escape_javascript(render("transactions")) %>");
    $("#row_for_transaction_<%= @transaction.id %>").effect("highlight", {}, 1000);
  <% end %>
<% else %>
  $('<div id="transaction-error"></div>')
		.html('<div class="alert">Please fix the following errors: <%= escape_javascript @transaction.errors.full_messages.to_sentence %></div>')
		.dialog({
			autoOpen: true,
			buttons: { 'OK' : function(){ $(this).dialog("destroy").remove(); } },
			modal: true,
			show: "fade",
			hide: "fade",
    });
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

app/views/transactions/edit.js.erb
$('<div id="transaction_dialog"></div>')
		.html('<%= escape_javascript render(:partial => 'fields.js') %>')
		.dialog({
			autoOpen: true,
			modal: true,
			title: 'Edit Transaction',
			buttons: { 'Update Transaction' :  function(){ $(this).find("form").submit(); }, 'Cancel' : function(){ $(this).dialog("close").remove(); } },
			show: "fade",
			hide: "fade",
			width: 420,
			close: function(event, ui) { $(this).dialog("destroy").remove(); }
    });

app/views/transactions/index.html.erb
<% if @transactions.any? %>
<ul id="sub-menu">
  <li class="buttonorange"><%= link_to " ⬇ Export to CSV", params.merge(:format => :csv, :action => "index") %></li>
  <li class="buttonorange"><%= link_to " Monthly Report", reports_monthly_transactions_path %></li>
</ul>
<% end %>

<h1>New Transaction</h1>
<div id="new-transaction-form">
  <%= render 'quick' %>
</div>

<div id="transactions">
  <%= render "transactions" %>
</div>

<script type="text/javascript" charset="utf-8">
  $(function() {
    Transactions.Form.init(".new_transaction");
  });
</script>

app/views/transactions/index.js.erb
$("#transactions").html("<%= escape_javascript(render("transactions")) %>");

app/views/transactions/monthly_report.html.erb
<ul id="sub-menu">
  <%= link_to '← All Transactions', transactions_path %>
</ul>

<h1>Monthly Financial Report
  <% if @periods.size > 1 %>
  <div class='floatr'>
    <%= select_tag 'fiscal_year', options_for_select(@periods, @fiscal_year), "data-url" => reports_monthly_transactions_url %>
  </div>
  <% end %>
</h1>

<% if @transactions.empty? %>
  <div class="no-occurence">
    <p>There is no transactions in this fiscal year (<%= @fiscal_year %>)</p>
  </div>
<% else %>
  <div id="pl_summary">
    <div class='card-inner'>
      <span id="total_income">Total Incomes: <span id="curr_income"><%= number_to_currency(Transaction.total_incomes(@transactions)) %></span></span>
    	<span id="total_expense">Total Expenses: <span id="curr_expense"><%= number_to_currency(Transaction.total_expenses(@transactions)) %></span></span>
    </div>
  </div>	 
  
  <% @transactions.group_by{|t| t.date.strftime "%Y %b" }.each do |date_str,transactions| %>
    <h2 class="date_period">
      <%= date_str %>
      <span class="total_right">
  	  Inc.: <span id="curr_income"><%= number_to_currency(Transaction.total_incomes(transactions)) %></span> | 
  	  Exp.: <span id="curr_expense"><%= number_to_currency(Transaction.total_expenses(transactions)) %></span>
  	</span>
    </h2>
    <ul>
    <% transactions.each do |transaction| %>
      <li class="transactions_list">
        <span id="t_date"><%= l transaction.date, :format => :short %></span>
    	<span id="t_type"><% if transaction.expense? %><span class="t_expense">Exp.</span><% else %><span class="t_income">Inc.</span> <% end %></span>
        <span id="t_amount"><%= link_to number_to_currency(transaction.total), transaction_path(transaction) %></span>
        <span id="t_note_short"><%= truncate(transaction.note, :length => 45) %></span>
    	<span id="t_category"><%= link_to transaction.category.name, expenses_category_path(transaction.category) unless transaction.category.nil? %></span>
    	<span id="t_project" style="max-width: 150px;"><%= link_to transaction.project.title, expenses_project_path(transaction.project) unless transaction.project.nil? %></span>
      </li>
    <% end %>
    </ul>
  <% end %>
<% end %>  

<script type="text/javascript" charset="utf-8">
  $(function() {
    Transactions.MonthlyReport.init();
  });
</script>

app/views/transactions/show.html.erb
<%= render "submenu" %>

<div class="receipt_top"></div>
<div class="receipt_mid">
  <p>
    <b>Date:</b>
  	<%= l @transaction.date %> <span class="type"><%= @transaction.expense? ? "EXPENSE" : "INCOME" %></span>
  </p>
  <p>
    <b>Description:</b>
  	<%= @transaction.note %>
  </p>
  <% if @transaction.subtotal != @transaction.total %>
  <p>
    <b>Subtotal:</b>
    <%= number_to_currency(@transaction.subtotal) %>
  </p>
  <% end %>
  <% if (@transaction.try(:tax1) || 0) > 0 %>
  <p>
    <b>Tax 1:</b>
  	<%= number_to_currency(@transaction.tax1) %>
  </p>
  <% end %>

  <% if (@transaction.try(:tax2) || 0) > 0 %>
  <p>
    <b>Tax 2:</b>
  	<%= number_to_currency(@transaction.tax2) %>
  </p>
  <% end %>

  <p>
    <b>Total:</b>
  	<%= number_to_currency(@transaction.total) %>
  </p>
  <p>
    <b>Category:</b>
    <%= link_to @transaction.category.name, expenses_category_path(@transaction.category) unless @transaction.category_id.nil? %>
  </p>
  <p>
    <b>Project:</b>
  	<%= link_to @transaction.project.title, expenses_project_path(@transaction.project) unless @transaction.project.nil? %>
  </p>
  <% if @transaction.receipt.present? %>
  <p>
    <b>Receipt:</b>
  	<%= @transaction.receipt %>
  </p>
  <% end %>
</div>
<div class="receipt_bot"></div>

app/views/transactions/update.js.erb
<% if @transaction.valid? %>
  $("#transaction_dialog").dialog("close");  
  location.reload();
<% else %>
   $('<div id="transaction-error"></div>')
		.html('<div class="alert">Please fix the following errors: <br /><%= escape_javascript @transaction.errors.full_messages.to_sentence %></div>')
		.dialog({
			autoOpen: true,
			buttons: { 'OK' : function(){ $(this).dialog("close"); } },
			show: "fade",
			hide: "fade",
    });
<% end %>