config/routes.rb
Projectlog::Application.routes.draw do
  root :to => 'dashboard#show'
    
  resources :transactions do
    collection do
      get 'reports/monthly', :action => 'monthly_report'
      get 'find_by_note'
    end
  end
  resources :subscriptions, :only => [:new, :create, :edit, :update] do
    collection do
      delete 'cancel'
      get 'current'
      get 'modify'
      put 'reactivate'
      get 'card_declined'
      get 'upgrade_required'
    end
    
    member do
      get 'success'
    end
  end
  get 'subscriptions/:slug/payments/:code', :controller => 'subscriptions', :action => 'receipt', :as => 'receipt_subscription_payment'
  
  resources :categories do
    member do
      get 'expenses'
    end
  end

  resource :dashboard do
    resources :activities, :controller => "dashboard/activities"
  end

  resources :project_statuses
  resources :profiles, :contacts
  
  resource :plan, :only => [:edit, :update]
  
  resources :customers do 
    resources :contacts
    resources :projects, :except => [:index]
    member do
      get 'projects', :to => "projects#by_customer"
    end
  end
  
  resources :invoices do
    member do
      get 'shared'
      get 'add_line_item'
      get 'prepare_email'
      post 'send_email'
      post 'sort'
    end
    collection do
      get 'overdue'
      post 'create_line_item'
      delete 'delete_line_item/:id', :action => 'delete_line_item'
    end
    resources :payments
  end
  
  resources :projects do
    collection do
      get 'closed'
      get 'quick'
    end
    
    resources :activities
    
    member do
      get 'expenses'
    end
  end
  
  resources :activities
  resources :transactions
  
  resources :reports do
    collection do
      get 'search'
    end
    member do
      get 'shared'
      post 'shared/approve', :action => 'approve'
    end
    resources :emails, :only => [ :new, :create ], :controller => 'reports/emails' do
      get 'contacts', :on => :collection
    end
  end
  
  resources :reports do
    member do
      post :timesheet
      put :approve
    end
  end
  
  resources :announcements, :only => [ :show ] do
    member { put :hide }
  end
  
  namespace :administr8te do
    resource :dashboard, :only => [ :show ], :controller => 'dashboard'
    resource :settings
    resources :clients, :only => [ :index ] do
      member do
        get 'summary'
        get 'profile'
        get 'transactions'
        get 'history'
      end
    end
    resources :plans
    resources :announcements
    resources :emailings
    resources :subscriptions, :only => [:index, :show]
    get '/audit', :controller => :audit_trails, :action => :index
    resource :logs, :only => [ :show ]
  end
  
  # allow "/users/login" and "/login"
  devise_for :user, :path_names => { :sign_up => "register", :sign_in => "login", :sign_out => "logout" }, 
                    :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get '/register', :to => 'registrations#new'
    get '/login', :to => 'devise/sessions#new'
    get '/logout', :to => 'devise/sessions#destroy'
  end
  post '/paypal/ipn' => 'paypal#ipn'
  match '/settings' => 'profiles#edit', :as => 'settings'
end

app/models/report.rb
# encoding: utf-8
class Report < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  
  attr_accessible :project_id, :start_date, :end_date, :slug, :approved, :approved_at, :approved_ip, :user_id
  validates_presence_of :user_id, :slug
  validate :start_date_must_be_smaller_than_end_date
  
  before_validation :generate_random_slug, :on => :create
  
  def to_param
    slug
  end
  
  def activities
    scoped = user.activities
    scoped = scoped.after(start_date) if start_date.present?
    scoped = scoped.before(end_date) if end_date.present?
    scoped.belonging_to_projects(projects)
  end
  
  def projects
    project.present? ? [project] : user.projects
  end
  
  def total_time
    activities.sum(:time)
  end
  alias_method :total_hours, :total_time
  
  def project_title
    project.present? ? project.title : "All Projects"
  end
    
  def description
    arr = [project_title]
    arr << "from #{I18n.l start_date, :format => :long}" if start_date.present?
    arr << "to #{I18n.l end_date, :format => :long}" if end_date.present?
    arr.join(" ")
  end
  
  def approve!(ip_address)
    self.approved = true
    self.approved_at = Time.zone.now
    self.approved_ip = ip_address
  end

  def to_csv(options={})
    CSV.generate(options) do |csv|
      csv << ["date","time","description","project"]
      activities.order('date ASC').each do |activity|
        csv << [I18n.localize(activity.date), activity.time, activity.description, activity.project.title]
      end
    end
  end
  
  private

  def generate_random_slug
    self.slug = Devise.friendly_token.downcase
  end
  
  def start_date_must_be_smaller_than_end_date
    if start_date.blank? && end_date.blank?
      errors.add(:base, "Start date or end date must be specified")
    else
      if start_date.present? && end_date.present? && start_date > end_date
        errors.add(:start_date, "must be smaller than end date")
      end
    end
  end

end

app/models/reports.rb
module Reports
  def self.table_name_prefix
    'reports_'
  end
end

app/models/reports/email.rb
class Reports::Email
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :to, :subject, :body, :from, :report_link, :reply_to
  
  validates_presence_of :to, :message => "Recipient is required"
  validates_presence_of :subject, :body, :from, :report_link, :reply_to
  validate :body_must_contain_report_link
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def body
    b = @body || ""
    b.gsub!("%{report_link}", report_link) unless report_link.blank?
    b
  end
  
  def deliver
    raise ArgumentError unless self.valid?
    ReportsMailer.report_shared_with_you(self).deliver
  end
  
  def body_must_contain_report_link
    errors.add(:body, "must contain a link to the report") unless report_link.present? && body.include?(report_link)
  end
  
  def persisted?
    false
  end  
end

app/controllers/reports/emails_controller.rb
class Reports::EmailsController < ApplicationController
  before_filter :authenticate_user!
  
  def new
    @report = Report.find_by_slug!(params[:report_id])
    @email = Reports::Email.new(:body => Settings["reports.email.body"],
                                :subject => Settings["reports.email.subject"], 
                                :report_link => shared_report_url(@report))
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def create
    @email = Reports::Email.new(params[:reports_email].merge(:from => "#{current_user.name} <notifications@projectlogapp.com>", :reply_to => current_user.email))
    if @email.valid?
      @email.deliver
    end
    respond_to do |format|
      format.js
    end
  end
  
  def contacts
    @contacts = current_user.connections.where("first_name LIKE ? OR last_name LIKE ?", "%#{params[:term]}%", "%#{params[:term]}%")
    
    respond_to do |format|
      format.html
      format.json { 
        render :json => @contacts.map{|contact| {label: "#{contact.first_name} #{contact.last_name}", value: contact.email} } 
      }
    end
  end
  
end

app/controllers/reports_controller.rb
# encoding: utf-8

class ReportsController < ApplicationController
  before_filter :authenticate_user!, except: [:shared, :approve ]
  set_tab :reports
  helper_method :sort_column, :sort_direction

  def new
    @report = Report.new
  end

  def create
    @report = current_user.reports.new(params[:report])
    if @report.save
      redirect_to @report
    else
      render "new"
    end
  end

  def show
    @report = Report.find_by_slug!(params[:id])
    @activities = @report.activities.includes(:project).search(params[:search]).order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html { @activities = @activities.page(params[:page]).per(10) }
      format.js { @activities = @activities.page(params[:page]).per(10) }
    end
  end

  def shared # Like show, except is public for everybody.
    @report = Report.find_by_slug!(params[:id])
    @activities = @report.activities.order('date ASC')
    respond_to do |format|
      format.html do
        render layout: "public"
      end
      format.pdf { render :text => PDFKit.new(render_to_string).to_pdf }
      format.csv {
        content = @report.to_csv
        content = content.encode("UTF-8")
        send_data content,
          filename:    "time_entries.csv",
          type:        "text/csv; charset=utf-8; header=present",
          disposition: "attachment"
      }
    end
  end

  def approve
    @report = Report.find_by_slug!(params[:id])

    if !@report.approved?
      @report.approve!(request.remote_ip)

      if @report.save
        redirect_to shared_report_path(@report)
      else
        redirect_to shared_report_path(@report), :notice => 'An error occured. Please try again.'
      end
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  private

    def sort_column
      Activity.column_names.include?(params[:sort]) ? params[:sort] : "date"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

end

app/helpers/reports/emails_helper.rb
module Reports::EmailsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
  def last_months_select(field_name, options = {}, how_many_months = 12)
    select_tag(field_name, last_months_select_options(how_many_months, options), options)
  end
  
  def last_months_select_options(how_many_months, options)
    first_day_of_current_month = Date.today.beginning_of_month
    array = (0...how_many_months).collect { |i| [(first_day_of_current_month - i.months).strftime("%B %Y"), first_day_of_current_month - i.months] }
    options_for_select(array, :selected => options[:selected] || first_day_of_current_month)
  end
  
  def report_project_select(field_name, projects, options = {})
    select_tag(field_name, options_for_select([["All Projects", ""]] + projects.collect { |project| [project.title, project.id] }, options[:selected]), options)
  end
end

app/views/reports/_activities.html.erb
<div id="activities">  
  
  <% if @activities.empty? %>
  <div class="no-occurence">
    <p>No Activities found.</p>
  </div>
  <% else %>
        <div id="activity-search">
	       <%= form_tag report_path(@report), :method => "get", :remote => true, :id => "activities_search" do %>
           <%= hidden_field_tag :direction, params[:direction] %>
           <%= hidden_field_tag :sort, params[:sort] %>
           <%= text_field_tag :search, params[:search] %>
           <span class="small submit"> <%= submit_tag "Filter", :name => nil %></span>
	       <div id="export" class="right">
	         <%= link_to 'Email Report', new_report_email_path(@report), :remote => true %> |
	         <%= link_to "Download PDF", params.merge(:format => :pdf, :action => "shared"), :target => "_blank" %> | 
	         <%= link_to "Export to CSV", params.merge(:format => :csv, :action => "shared") %>  
	      </div>
        </div>
     <% end %>
   
  <table class='activities'>
    <tr>
      <th width="10%"><%= sortable "date" %></th>
      <th width="8%"><%= sortable "time" %></th>
      <th><%= sortable "description" %></th>
      <th><%= sortable "project_id", { }, "Project" %></th>
      <th></th>
    </tr>

    <% @activities.each do |activity| %>
      <%= content_tag :tr, :id => "row_for_activity_#{activity.id}" do %>
        <%= render :partial => "reports/activity", :object => activity %>
      <% end %>
    <% end %>

    <tr class="total">
      <th class="total right">TOTAL</th>
      <th id="report_total_time"><%= number_with_delimiter(@report.total_time) %></th>
      <th class="total_in_days" id="report_total_in_days"><%= activities_to_days(@report.total_time) %></th>
      <th></th>
      <th></th>
    </tr>
  </table>

  <div class="right">
    <%= paginate @activities %>
  </div>
  
<% end %>
</div>

app/views/reports/_search_form.html.erb
<% if @report.errors.any? %>
  <div id="error_explanation" class="alert">
    <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being generated:</h2>

    <ul>
    <% @report.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div id="quick_search">
  <h2>Quick Search</h2>
  <%= form_for @report, :url => reports_path, :html => { :method => :post, :id => "new_quick_report" } do |f| %>
    <p>Show hours for <%= f.collection_select :project_id, current_user.projects.all, :id, :title_and_client, :include_blank => "All Projects", :id => "quick_search_project_id" %> during 
    <%= last_months_select :"report[start_date]", :selected => @report.start_date, :id => "quick_search_start_date" %>
    <%= f.hidden_field :end_date, :value => (@report.start_date || Date.today.beginning_of_month) + 1.month - 1.second, :id => "quick_search_end_date" %>
    <span class="submit"><%= f.submit "Create Timesheet", 'data-disable-with' => 'Please wait...' %></span>
    <%= image_tag("indicator.gif", :class => "loading", :style => "display: none") %>
    </p>
  <% end %>  
</div>

<div id="advanced_search" style="display: none">
  <h2>Advanced Search</h2>
  <%= form_for @report, :url => reports_path(:form => "advanced"), :html => { :method => :post, :id => "new_advanced_report" } do |f| %>

 <p>Show hours for <%= f.collection_select :project_id, current_user.projects.all, :id, :title_and_client, :include_blank => "All Projects", :id => "advanced_search_project_id" %>
   from <%= f.text_field :start_date, :size => 12, :class => "date" %>
   to <%= f.text_field :end_date, :size => 12, :class => "date" %>
   <span class="submit"><%= f.submit 'Create Timesheet', 'data-disable-with' => 'Please wait...' %></span>
   <%= image_tag("indicator.gif", :class => "loading", :style => "display: none") %>  
 </p>
  <% end %>
</div>

<%= link_to "Show/Hide Advanced Search", "#", :id => "toggle_search_form" %>

<% if current_user.reports.any? %>
  <h4>Recent Reports</h4>
  <ul id="recent-reports">
  <% current_user.reports.order("created_at DESC").limit(5).each do |report| %>
    <li><%= link_to report.description, report %>
	<% if report.approved? %><span class="approved">Approved</span><% end %>
	</li>
  <% end %>
  </ul>
<% end %>

app/views/reports/_send_timesheet.html.erb
<%= form_tag(:id => 'send_timesheet_form', :style => 'display:none') do %>
  <div class="field">
    <%= label_tag :email, "Recipient" %><br />
    <%= select_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :subject %><br />
    <%= text_field_tag :subject %>
  </div>
  <div class="field">
    <%= label_tag :message %><br />
    <%= text_field_tag :message %>
  </div>
  <div class="actions">
    <%= submit_tag 'Send' %> or
    <%= link_to 'Cancel', '#', :onclick => "$('#send_timesheet_form').slideUp()" %>
  </div>
<% end %>

app/views/reports/_shared_activities.html.erb
<% if @activities.empty? %>
  <div class="no-occurence">
    <p>No activity matches your search criteria.</p>
  </div>
<% else %>   
  <table class='activities'>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Description</th>
      <th>Project</th>
    </tr>

    <% @activities.each do |activity| %>
    <tr>
      <td class="date"><%= l activity.date, format: :short %></td>
      <td class="time"><%= activity.time %></td>
      <td class="description"><%= activity.description %></td>
      <td class="project"><%= activity.project.title %></td>
    </tr>
    <% end %>

    <tr class="total">
      <th class="total right">TOTAL</th>
      <th><%= number_with_delimiter(@report.total_time) %></th>
      <th></th>
      <th></th>
    </tr>
  </table>
  
<% end %>

app/views/reports/activities_destroy.js.erb
$("#row_for_activity_<%= @activity.id %>").fadeOut();
$("#report_total_time").html('<%= number_with_delimiter(@report.total_time) %>');
$(".total_in_days").html('<%= activities_to_days(@report.total_time) %>');

app/views/reports/activities_update.js.erb
<% if @activity.valid? %>
  $("#row_for_activity_<%= @activity.id %>").html("<%= escape_javascript render(@activity) %>");
  // Update total sum
  $("#report_total_time").html('<%= number_with_delimiter(@report.total_time) %>');
<% else %>
  alert("Please fix the following1 errors: <%= @activity.errors.full_messages.to_sentence %>.");
<% end %>

app/views/reports/new.html.erb
<% if @current_user.activities.empty? %>
  <div class="no-occurence">
    <p>You will be able to create reports as soon as you record Activities.</p>
  </div>
<% else %>
  <div id="activity_search">
    <%= render :partial => "search_form" %>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
  $(function() {
    Reports.New.init();
  });
</script>

app/views/reports/search.js.erb
$("#activities").html("<%= escape_javascript(render "activities") %>");

app/views/reports/search.pdf.erb
<head>
	<title>Timesheet</title>
<style>
  @media print {
   table {
	border-spacing: 0px;
	width: 100%;
	text-align: left;
	font: 11px;
   } 
   table th {
      font-weight: bold;
      padding: 8px;
    }
    #header th {
	border-bottom: 1px solid #eaeaea;
    }
    #total th {
	border-top: 2px solid #eaeaea;
    }
    table td {
    padding: 8px;
    margin-right: 10px; 
    }
    #period {
	font-weight: bold;
	}
	.date {
	width:80px;
	}
	.time {
	width:40px;
	}
	.sum {
	text-align:right; 
	padding-left:10px;
	}
  }
</style>
</head>

<div id="activities">  
  <h1>Timesheet</h1>  

  <% if @activities.empty? %>
  <div class="no-occurence">
    <p>
      No activity matches your search criteria.
    </p>
  </div>
  <% else %>
  
  <p id='period'><%= current_user.full_name %>'s hours from <%= :start_date %> to <%= :end_date %></p>
  <p>Project: <b><%= :project_title %></b></p>
  <br/>

  <table>
    <tr id="header">
      <th>Date</th>
      <th>Time</th>
      <th>Description</th>
    </tr>

    <% @activities.each do |activity| %>
    <tr>
      <td class="date"><%= l activity.date, :format => :short %></td>
      <td class="time"><%= activity.time %></td>
      <td class="description"><%= activity.description %></td>      
    </tr>
    <% end %>

    <tr id="total">
      <th class="sum">TOTAL</th>
      <th><%= @total_time %></th>
      <th></th>
    </tr>
  </table>
  <% end %>
</div>

app/views/reports/shared.html.erb
<%= render 'shared_header' unless @skip_approve %>
<section id="main-content">
  <section id="content" role="main">
      
    <h1><%= @report.description %> 
	  <span id="total_report">TOTAL <%= number_with_delimiter(@report.total_time) %></span>
	</h1>

	<div id="activities">  
	  <%= render "shared_activities" %>
	</div>

  </section>
</section>

app/views/reports/shared.js.erb
$("#activities").html("<%= escape_javascript(render "shared_activities") %>");

app/views/reports/shared.pdf.erb
<head>
  <title>Timesheet</title>
  <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
  <style>
    @media print {
      table {
        border-spacing: 0px;
        width: 100%;
        text-align: left;
        font: 11px;
      }
      table th {
        font-weight: bold;
        padding: 8px;
      }
      #header th {
        border-bottom: 1px solid #eaeaea;
      }
      #total th {
        border-top: 2px solid #eaeaea;
      }
      table td {
        padding: 8px;
        margin-right: 10px;
      }
      #period {
        font-weight: bold;
      }
      .date {
        width: 80px;
      }
      .time {
        width: 40px;
      }
      .sum {
        text-align: right;
        padding-left: 10px;
      }
      .hours_to_days {
        text-align: left;
      }
    }
  </style>
</head>

<div id="activities">
  <h1>Timesheet</h1>

  <% if @activities.empty? %>
    <div class="no-occurence">
      <p>
        No activity matches your search criteria.
      </p>
    </div>
  <% else %>

    <p id='period'><%= @report.user.full_name %>'s hours <%= @report.description %></p>

    <p>Project: <b><%= @report.project_title %></b></p>
    <% if params[:search] %>
      <p>Search terms: <b><%= params[:search] %></b></p>
    <% end %>
    <br/>

    <table>
      <tr id="header">
        <th>Date</th>
        <th>Time</th>
        <th>Description</th>
      </tr>

      <% @activities.each do |activity| %>
        <tr>
          <td class="date"><%= l activity.date, :format => :short %></td>
          <td class="time"><%= activity.time %></td>
          <td class="description"><%= activity.description %></td>
        </tr>
      <% end %>

      <tr id="total">
        <th class="sum">TOTAL</th>
        <th><%= @report.total_time %></th>
        <th class="hours_to_days">
          <% if @report.user.profile.hours_per_day.present? %>
            [ <%= number_with_precision(@report.total_time / @report.user.profile.hours_per_day, precision: 2) %> days ]
          <% end %>
        </th>
      </tr>
    </table>
  <% end %>
</div>

app/views/reports/show.csv.erb
date,time,description,project
<% @activities.each do |activity| %>
<%= l activity.date %>,<%= activity.time %>,"<%= activity.description %>",<%= activity.project.title %>
<% end %>

app/views/reports/show.js.erb
$("#activities").html("<%= escape_javascript(render "activities") %>");